### ISSUE TITLE
Kaa alphabet update

### ISSUE THREAD

**Issue by sharapat** [apertium/apertium-kaa#2]
Now in karakalpak language spelling of these letters o', u', g', a', n' are changed to ó, ú, ǵ, á and ń. Should I change these too? There is karakalpak language book for 10 class pupils http://n.ziyouz.com/books/qaraqalpaq_kitapxanasi/sabaqliqlar/10-klass/Qaraqalpaq%20tili.%2010-klass%20(2017).pdf

**Comment by sharapat** [comment]
I changed all changed letters in my repo which I forked. should I change like that or is there other way to do it?

**Comment by jonorthwash** [comment]
There are two possible solutions:
1. Change the transducer (`lexc`, `twol` files), the disambiguator (`rlx`), and all dictionaries, lexical selection modules, and structural transfer modules that have been written for Qaraqalpaq.
   - We would want to also set up a transliteration transducer as with [apertium-crh](http://github.com/apertium/apertium-crh) to analyse the other orthography.
2. Keep the apostrophe orthography as the one Apertium works with, and add a transliteration transducer for the new one.

The first one is a lot more work, but the new orthography is enough better that I think we should do it.  @ftyers, @IlnarSelimcan, @MemduhG, what do you think?

**Comment by ftyers** [comment]
I agree, we should go with the new orthography. It will make rule-writing a lot easier, and we can write a transliterator to the old one if necessary.

**Comment by jonorthwash** [comment]
> I changed all changed letters in my repo which I forked. should I change like that or is there other way to do it?

@sharapat, if we go with the first option, then yes, we'd incorporate the work you did in your fork.

However, it's more complicated than just fixing the lexical items in the `lexc` file.  The morphophonology and `twol` modules also would have to be fixed, and it would not be as trivial as for the lexicon—I would be happy to do the necessary restructuring though.

**Comment by IlnarSelimcan** [comment]
+1 to the first option.

**Comment by jonorthwash** [comment]
> we can write a transliterator to the old one if necessary.

We should definitely do this.  E.g., despite the change having happened a year or two ago (??), [kaa.wikipedia.org](http://kaa.wikipedia.org/) and the [IBT bible translation](https://ibtrussia.org/en/text?m=KRKL) are still in the old (pre-2009) orthography.

**Comment by sharapat** [comment]
> > we can write a transliterator to the old one if necessary.
> 
> We should definitely do this. E.g., despite the change having happened a year or two ago (??), [kaa.wikipedia.org](http://kaa.wikipedia.org/) and the [IBT bible translation](https://ibtrussia.org/en/text?m=KRKL) are still in the old (pre-2009) orthography.

Because, holders of Qaraqalpaq language don't really support these. Just a few people write in wiki.

**Comment by jonorthwash** [comment]
@sharapat, could you give some more background about when the change happened and how widely used it is?

**Comment by MambetniyazovAmir** [comment]
all documents and books  are written in a new alphabet

**Comment by sharapat** [comment]
> @sharapat, could you give some more background about when the change happened and how widely used it is?

I will try to find the low about it.

**Comment by MambetniyazovAmir** [comment]
https://ru.wikipedia.org/wiki/%D0%9A%D0%B0%D1%80%D0%B0%D0%BA%D0%B0%D0%BB%D0%BF%D0%B0%D0%BA%D1%81%D0%BA%D0%B8%D0%B9_%D1%8F%D0%B7%D1%8B%D0%BA

**Comment by MambetniyazovAmir** [comment]
The last changes to the new Karakalpak alphabet were made in 2016: instead of letters with apostrophes, they were entered with strokes above the letters.

**Comment by MambetniyazovAmir** [comment]
And also about a new letter c and ch. For example, before a word "position" translated as "pozitsya"  now it should be poziciya.

**Comment by jonorthwash** [comment]
> The last changes to the new Karakalpak alphabet were made in 2016

By whom?  How widely have they been adopted?  That is, do most(?) Qaraqalpaq speakers accept the new orthography and use it in place of the old one now?

**Comment by sharapat** [comment]
I guess, We should change it to new one. Because all documentations and books are written in a new orthography.

**Comment by jonorthwash** [comment]
@sharapat, okay, then let's do this:

When you finish converting the entire lexicon, submit a PR.  I will fix the morphophonology and we can start working on a transliterator.

**Comment by sharapat** [comment]
> @sharapat, okay, then let's do this:
> 
> When you finish converting the entire lexicon, submit a PR. I will fix the morphophonology and we can start working on a transliterator.

no, problem)

**Comment by IlnarSelimcan** [comment]
apertium-kaa.kaa.lexc is update-to-date now with the recent alphabet, see: https://github.com/apertium/apertium-kaa/commit/289129dd18834706809d940c2aed92b5378c9fb6

apertium-kaa.kaa.twol still needs to be updated.

**Comment by jonorthwash** [comment]
I updated apertium-kaa.kaa.twol in 8b2227b; now we need to test it!

**Comment by jonorthwash** [comment]
I made a transliterator between the new orthography and the old orthography (probably incomplete) and compiled a transducer that will accept both (59322658f040989146f0b26bf404ac824cb0f55e).  Here's a comparison of the coverage before any orthography updates (54b29b3c1040fb45ead0155daa5ca3487ac934b5) and the coverage of the multi-script transducer:

| corpus | size | old transducer | multi-script transducer |
|--------|--------|--------|---------|
| botanix | 16K~20K | 77.13% | 64.84% |
| megaline | 35K~48K | 80.57% | 62.10% |
| wikipedia | 147K~201K | 79.98% | 63.14% |
| NT | 188K-262K | 87.91% | 68.39% |

There seems to be some difference in how tokenisation works, which might be primarily what's leading to the lower numbers?  In all cases, more tokens receive an analysis in the multi-script transducer.  I'll investigate further :)

**Comment by sharapat** [comment]
I have tested updated apertium-kaa.kaa.twol in short story. Coverage is 92.18%.

**Comment by jonorthwash** [comment]
Aha, I didn't have spellrelax integrated.  Now (964ddc3) done.  Updated numbers:

| corpus | size | old transducer | multi-script transducer |
|--------|--------|--------|---------|
| botanix | 16K~17K | 77.13% | 73.41% |
| megaline | 35K~39K | 80.57% | 73.29% |
| wikipedia | 147K~162K | 79.98% | 74.12% |
| NT | 188K~212K | 87.91% | 79.72% |

Still needs some work, but we're getting there!

**Comment by sharapat** [comment]
> I have tested updated apertium-kaa.kaa.twol in short story. Coverage is 92.18%.

I will add the unknown words.

**Comment by jonorthwash** [comment]
> I have tested updated apertium-kaa.kaa.twol in short story. Coverage is 92.18%.

@sharapat, are there any forms that you think should be working that aren't?

**Comment by sharapat** [comment]
> > I have tested updated apertium-kaa.kaa.twol in short story. Coverage is 92.18%.
> 
> @sharapat, are there any forms that you think should be working that aren't?

I will check it out.

**Comment by jonorthwash** [comment]
I fixed some `twol` rules (7949690) and got more improvements!

| corpus | size | old transducer | multi-script transducer |
|--------|--------|--------|---------|
| botanix | 16K~17K | 77.13% | 76.52% |
| megaline | 35K~36K | 80.57% | 79.62% |
| wikipedia | 147K~151K | 79.98% | 78.93% |
| NT | 188K~196K | 87.91% | 85.19% |

We're almost there!

**Comment by jonorthwash** [comment]
Got rid of `{ъ}` in `lexc` (28cc13d) and now:

| corpus | size | old transducer | multi-script transducer |
|--------|--------|--------|---------|
| botanix | 16K | 77.13% | 77.11% |
| megaline | 35K~36K | 80.57% | 80.52% |
| wikipedia | 147K~150K | 79.98% | 79.39% |
| NT | 188K~190K | 87.91% | 87.29% |

So close!

**Comment by jonorthwash** [comment]
The unknown forms in fact appear to be _identical_!

If correct, this would mean we have successfully converted the transducer to the new orthography _and also_ made a perfect transliterator!?!?

**Comment by sharapat** [comment]
I tested last version of apertium-kaa.twol with my local apertium-kaa.lexc file. Coverage is 99.03%.

**Comment by IlnarSelimcan** [comment]
@jonorthwash With regular updates on coverage numbers, you make your work on twol as exciting as a tense NHL or Champions League game!

**Comment by jonorthwash** [comment]
Haha, actually the unknown forms lists are a little different.  I think there are some corner cases that still aren't covered by the updated `twol`, but we can fix those as we go.  In any case, the new orthography works for the most part, so we can probably close this issue.

**Comment by IlnarSelimcan** [comment]
Agreed. Thanks for taking care of this @jonorthwash !
